const DEMO_MUSICIANS = [
  {
    id: 'demo-musician-1',
    name: 'Marko Petrović',
    primaryInstrument: 'Bubnjevi',
    genres: 'Pop, Rock, Funk',
    city: 'Beograd',
    priceFromEur: 120,
    priceToEur: 220,
    experienceYears: 11,
    bio: 'Session bubnjar sa iskustvom u svadbama, klupskim i korporativnim nastupima.',
    img: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=8aGhZQkoFbQ',
    rating: 4.8,
    isFeatured: true,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-2',
    name: 'Jelena Kostić',
    primaryInstrument: 'Vokal',
    genres: 'Pop, Narodna, Zabavna',
    city: 'Novi Sad',
    priceFromEur: 150,
    priceToEur: 280,
    experienceYears: 9,
    bio: 'Lead vokal i back-vokal sa širokim repertoarom za veselja i hotelske svirke.',
    img: 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=1ZYbU82GVz4',
    rating: 4.9,
    isFeatured: true,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-3',
    name: 'Stefan Ilić',
    primaryInstrument: 'Klavijature',
    genres: 'Narodna, Pop, Evergreen',
    city: 'Niš',
    priceFromEur: 100,
    priceToEur: 190,
    experienceYears: 7,
    bio: 'Klavijaturista i aranžer, spreman za zamene i dugoročne angažmane.',
    img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=H3Uhu6R5uJ8',
    rating: 4.7,
    isFeatured: false,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-4',
    name: 'Nemanja Jović',
    primaryInstrument: 'Gitara',
    genres: 'Rock, Blues, Pop',
    city: 'Kragujevac',
    priceFromEur: 90,
    priceToEur: 170,
    experienceYears: 6,
    bio: 'Ritam i lead gitara, nastupi po dogovoru u celoj Srbiji.',
    img: 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?auto=format&fit=crop&w=1200&q=80',
    videoUrl: '',
    rating: 4.6,
    isFeatured: false,
    isAvailable: false,
    demo: true,
  },
  {
    id: 'demo-musician-5',
    name: 'Ana Vujović',
    primaryInstrument: 'Violina',
    genres: 'Evergreen, Pop, Klasika',
    city: 'Beograd',
    priceFromEur: 140,
    priceToEur: 260,
    experienceYears: 10,
    bio: 'Violinistkinja za ceremonije, prijeme i premium event nastupe.',
    img: 'https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?auto=format&fit=crop&w=1200&q=80',
    videoUrl: '',
    rating: 4.9,
    isFeatured: true,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-6',
    name: 'Dušan Milenković',
    primaryInstrument: 'Bas gitara',
    genres: 'Funk, Pop, Rock',
    city: 'Novi Sad',
    priceFromEur: 95,
    priceToEur: 180,
    experienceYears: 8,
    bio: 'Pouzdan basista za zamene i stalne postave bendova.',
    img: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80',
    videoUrl: '',
    rating: 4.7,
    isFeatured: false,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-7',
    name: 'Ivana Simić',
    primaryInstrument: 'Saksofon',
    genres: 'Jazz, Pop, Lounge',
    city: 'Niš',
    priceFromEur: 130,
    priceToEur: 240,
    experienceYears: 9,
    bio: 'Saksofon performansi za klubove, lounge večeri i korporativne evente.',
    img: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
    videoUrl: '',
    rating: 4.8,
    isFeatured: false,
    isAvailable: true,
    demo: true,
  },
  {
    id: 'demo-musician-8',
    name: 'Petar Đorđević',
    primaryInstrument: 'Harmonika',
    genres: 'Narodna, Starogradska',
    city: 'Kraljevo',
    priceFromEur: 110,
    priceToEur: 210,
    experienceYears: 12,
    bio: 'Harmonikaš za svadbe i veselja, repertoar po želji domaćina.',
    img: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    videoUrl: '',
    rating: 4.8,
    isFeatured: false,
    isAvailable: true,
    demo: true,
  },
];

export function getDemoMusicians() {
  return DEMO_MUSICIANS.map((m) => ({ ...m }));
}
