export const songs = [
  // 1. MUSKE ZABAVNE (108 PESAMA)
  { id: 1, title: 'Cesarica', artist: 'Oliver D.', type: 'Muške Zabavne' },
  { id: 2, title: 'Ruka za spas', artist: 'Saša K.', type: 'Muške Zabavne' },
  { id: 3, title: 'Volim osmeh tvoj', artist: 'Toše P.', type: 'Muške Zabavne' },
  { id: 4, title: 'Ti i ja', artist: 'Generacija 5', type: 'Muške Zabavne' },
  { id: 5, title: 'Nije za nju', artist: 'Oliver Mandić', type: 'Muške Zabavne' },
  { id: 6, title: 'Mesec u vodi', artist: 'Željko S.', type: 'Muške Zabavne' },
  { id: 7, title: 'Mađarica', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 8, title: 'Pevaj', artist: 'Ogi', type: 'Muške Zabavne' },
  { id: 9, title: 'Zenica bluz', artist: 'Zabranjeno Pušenje', type: 'Muške Zabavne' },
  { id: 10, title: 'Ružice moja ruska', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 11, title: 'Fenomenalno', artist: 'Ćira', type: 'Muške Zabavne' },
  { id: 12, title: 'Sex bomb', artist: 'Tom Jones', type: 'Muške Zabavne' },
  { id: 13, title: 'Pusti modu', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 14, title: 'Nisam se bogat rodio', artist: 'Aco P.', type: 'Muške Zabavne' },
  { id: 15, title: 'Nije do mene', artist: 'Željko J.', type: 'Muške Zabavne' },
  { id: 16, title: 'Za dobra stara vremena', artist: 'Novi Fosili', type: 'Muške Zabavne' },
  { id: 17, title: 'Sele moja', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 18, title: 'Starim ja', artist: 'Oliver D.', type: 'Muške Zabavne' },
  { id: 19, title: 'Zeni nam se Vukota', artist: 'Zabranjeno Pušenje', type: 'Muške Zabavne' },
  { id: 20, title: 'Ako su to samo bile lazi', artist: 'Plavi Orkestar', type: 'Muške Zabavne' },
  { id: 21, title: 'Kotor', artist: 'Galija', type: 'Muške Zabavne' },
  { id: 22, title: 'Andrea', artist: 'Regata', type: 'Muške Zabavne' },
  { id: 23, title: 'Ćuškije', artist: 'Dino Merlin', type: 'Muške Zabavne' },
  { id: 24, title: 'La sate mi kantare', artist: 'Toto Cutugno', type: 'Muške Zabavne' },
  { id: 25, title: 'Sve još miriše na nju', artist: 'Parni Valjak', type: 'Muške Zabavne' },
  { id: 26, title: 'Jorgovani', artist: 'Dino Merlin', type: 'Muške Zabavne' },
  { id: 27, title: 'Oprosti', artist: 'Bebek', type: 'Muške Zabavne' },
  { id: 28, title: 'Jabuke i vino', artist: 'Zana # Bebek', type: 'Muške Zabavne' },
  { id: 29, title: 'Smijehom strah', artist: 'Merlin', type: 'Muške Zabavne' },
  { id: 30, title: 'Našoj ljubavi je kraj', artist: 'Oliver D.', type: 'Muške Zabavne' },
  { id: 31, title: 'Sanjam', artist: 'Indexi', type: 'Muške Zabavne' },
  { id: 32, title: 'Lejla', artist: 'Hari Mata Hari', type: 'Muške Zabavne' },
  { id: 33, title: 'Stvari lagane', artist: 'Boris Novković', type: 'Muške Zabavne' },
  { id: 34, title: 'Besamo mucho', artist: 'Andrea Bocelli', type: 'Muške Zabavne' },
  { id: 35, title: 'Wind of change', artist: 'Scorpions', type: 'Muške Zabavne' },
  { id: 36, title: 'Knock knock', artist: 'Bob Dylan', type: 'Muške Zabavne' },
  { id: 37, title: 'Sve ove godine', artist: 'Indexi', type: 'Muške Zabavne' },
  { id: 38, title: 'Mokre ulice', artist: 'Dejan Cukić', type: 'Muške Zabavne' },
  { id: 39, title: 'Hotel Balkan', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 40, title: '17 godina', artist: 'Magazin', type: 'Muške Zabavne' },
  { id: 41, title: 'Ne daj da te rade', artist: 'Željko S.', type: 'Muške Zabavne' },
  { id: 42, title: 'Cico', artist: 'Ogi', type: 'Muške Zabavne' },
  { id: 43, title: 'Stranac u noći', artist: 'Massimo', type: 'Muške Zabavne' },
  { id: 44, title: 'Prava stvar', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 45, title: 'Godinama varao si me', artist: 'Magazin', type: 'Muške Zabavne' },
  { id: 46, title: 'Ne spominji ljubav', artist: 'Željko S.', type: 'Muške Zabavne' },
  { id: 47, title: 'Imati pa nemati', artist: 'Džej', type: 'Muške Zabavne' },
  { id: 48, title: 'Čija si nisi', artist: 'Amadeus', type: 'Muške Zabavne' },
  { id: 49, title: 'U mojim venama', artist: 'Aco P.', type: 'Muške Zabavne' },
  { id: 50, title: 'Da muški poginem', artist: 'Saša M.', type: 'Muške Zabavne' },
  { id: 51, title: 'Nesanica', artist: 'Ivkova slava', type: 'Muške Zabavne' },
  { id: 52, title: 'Poklonite mi nju za rodjendan', artist: 'Saša M.', type: 'Muške Zabavne' },
  { id: 53, title: 'Kopriva', artist: 'Al Dino', type: 'Muške Zabavne' },
  { id: 54, title: 'Upali svetlo', artist: 'Aca Lukas', type: 'Muške Zabavne' },
  { id: 55, title: 'Lažu te', artist: 'Amadeus Band', type: 'Muške Zabavne' },
  { id: 56, title: 'Igra bez granica', artist: 'Toše P.', type: 'Muške Zabavne' },
  { id: 57, title: 'Pesma lagana', artist: 'Parni Valjak', type: 'Muške Zabavne' },
  { id: 58, title: 'Zaboravljeni', artist: 'Piloti', type: 'Muške Zabavne' },
  { id: 59, title: 'Ostala si uvjek ista', artist: 'Mišo Kovač', type: 'Muške Zabavne' },
  { id: 60, title: 'Dirlija', artist: 'Crvena Jabuka', type: 'Muške Zabavne' },
  { id: 61, title: 'Godina', artist: 'Tifa', type: 'Muške Zabavne' },
  { id: 62, title: 'Tajna veza', artist: 'Bijelo Dugme', type: 'Muške Zabavne' },
  { id: 63, title: 'Korak do dna', artist: 'Saša K.', type: 'Muške Zabavne' },
  { id: 64, title: 'Kao ptica na mom dlanu', artist: 'Piloti', type: 'Muške Zabavne' },
  { id: 65, title: 'Stranac u noći', artist: 'Oliver D.', type: 'Muške Zabavne' },
  { id: 66, title: 'Balkan', artist: 'Zdravko Čolić', type: 'Muške Zabavne' },
  { id: 67, title: 'Neko te ima noćas', artist: 'Van Gogh', type: 'Muške Zabavne' },
  { id: 68, title: 'Hiljadu puta', artist: 'Neverne Bebe', type: 'Muške Zabavne' },
  { id: 69, title: 'Dobra vila', artist: 'Boris Novković', type: 'Muške Zabavne' },
  { id: 70, title: 'Uvenuće jasmon beli', artist: 'Šaban Šaulić', type: 'Muške Zabavne' },
  { id: 71, title: 'Ako to se zove ljubav', artist: 'Tony Cetinski', type: 'Muške Zabavne' },
  { id: 72, title: 'Blagoslov za kraj', artist: 'OT Band', type: 'Muške Zabavne' },
  { id: 73, title: 'Dabogda', artist: 'Dino & Hari', type: 'Muške Zabavne' },
  { id: 74, title: 'Tako malo', artist: 'Vlado Georgiev', type: 'Muške Zabavne' },
  { id: 75, title: 'Cipela', artist: 'Marko Kon', type: 'Muške Zabavne' },
  { id: 76, title: 'Nemoj da me gledas sa visine', artist: 'Riblja Čorba', type: 'Muške Zabavne' },
  { id: 78, title: 'Koji dobrom mila moja', artist: 'Željko S.', type: 'Muške Zabavne' },
  { id: 79, title: 'Ljepša od noći', artist: 'Dado P.', type: 'Muške Zabavne' },
  { id: 80, title: 'Nepopravljivo', artist: 'Dženan L.', type: 'Muške Zabavne' },
  { id: 81, title: 'Ne verujem ja', artist: 'Željko V.', type: 'Muške Zabavne' },
  { id: 82, title: 'Niko kao ti', artist: 'Aca L # Danijela', type: 'Muške Zabavne' },
  { id: 83, title: 'Cveta', artist: 'Šaban Šaulić', type: 'Muške Zabavne' },
  { id: 84, title: 'Ja kunem se u ljubav', artist: 'Tony Cetinski', type: 'Muške Zabavne' },
  { id: 85, title: 'Živi bili pa videli', artist: 'Aca Lukas', type: 'Muške Zabavne' },
  { id: 86, title: 'Zmija i zaba', artist: 'Oskar', type: 'Muške Zabavne' },
  { id: 87, title: 'Ja baraba a ti vila', artist: 'B. Panters', type: 'Muške Zabavne' },
  { id: 88, title: 'Još ti se nadam', artist: 'Emina J.', type: 'Muške Zabavne' },
  { id: 89, title: 'Of Jano Jano', artist: 'Milosav Ilić', type: 'Muške Zabavne' },
  { id: 90, title: 'Ubijas me usnama', artist: 'Toše P.', type: 'Muške Zabavne' },
  { id: 91, title: 'Mislis li na mene', artist: 'Amadeus', type: 'Muške Zabavne' },
  { id: 92, title: 'Kolo... Luda luda', artist: 'Zabavna', type: 'Muške Zabavne' },
  { id: 93, title: 'Da šutiš', artist: 'Dino M.', type: 'Muške Zabavne' },
  { id: 94, title: 'Dama', artist: 'Dado P.', type: 'Muške Zabavne' },
  { id: 95, title: 'Dva minuta', artist: 'Sergej Ć.', type: 'Muške Zabavne' },
  { id: 96, title: 'Ljubavi', artist: 'Željko J.', type: 'Muške Zabavne' },
  { id: 97, title: 'Ja baraba', artist: 'Davor Badrov', type: 'Muške Zabavne' },
  { id: 98, title: 'Ljubavi moja tugo', artist: 'Petar Grašo', type: 'Muške Zabavne' },
  { id: 99, title: 'Fali mi ljubav', artist: 'Dado P.', type: 'Muške Zabavne' },
  { id: 100, title: 'Traži', artist: 'Sergej Ć.', type: 'Muške Zabavne' },
  { id: 101, title: 'Kosa do ramena', artist: 'Dženan L.', type: 'Muške Zabavne' },
  { id: 102, title: 'Loša', artist: 'Dženan', type: 'Muške Zabavne' },
  { id: 103, title: 'LJubim u prolazu', artist: 'Dženan L.', type: 'Muške Zabavne' },
  { id: 104, title: 'Putnička', artist: 'Dženan', type: 'Muške Zabavne' },
  { id: 105, title: 'Bombona', artist: 'Dženan L.', type: 'Muške Zabavne' },
  { id: 106, title: 'Opet si pogrešila', artist: 'Tony C.', type: 'Muške Zabavne' },
  { id: 107, title: 'Zena za sva vremena', artist: 'Milan Stanković', type: 'Muške Zabavne' },
  { id: 108, title: 'Voli me ne voli me', artist: 'Lexington', type: 'Muške Zabavne' },

  // -------------------------------------------------------------
  // 3. ZENSKE ZABAVNE (213 PESAMA)
  // -------------------------------------------------------------
  { id: 3001, title: 'Dani i godine', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3002, title: 'Zagrli', artist: 'Goca Tržan', type: 'Ženske Zabavne' },
  { id: 3003, title: 'Zlatni dan', artist: 'Bisera Veletanlić', type: 'Ženske Zabavne' },
  { id: 3004, title: 'Vrijeme prastanja', artist: 'Marija Šerifović', type: 'Ženske Zabavne' },
  { id: 3005, title: 'Bitanga i princeza', artist: 'Bijelo Dugme (Cover)', type: 'Ženske Zabavne' },
  { id: 3006, title: 'Marija Magdalena', artist: 'Doris Dragović', type: 'Ženske Zabavne' },
  { id: 3007, title: 'Beskrajno', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3008, title: 'Godina Tifa', artist: 'Tifa (Cover)', type: 'Ženske Zabavne' },
  { id: 3009, title: 'Jos jedan krug', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3010, title: 'Godinama', artist: 'Ivana Banfić', type: 'Ženske Zabavne' },
  { id: 3011, title: 'Kreni', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3012, title: 'Prava zena', artist: 'Lana Jurcevic', type: 'Ženske Zabavne' },
  { id: 3013, title: 'Mili moj', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3014, title: 'Dva', artist: 'Tijana Dapčević', type: 'Ženske Zabavne' },
  { id: 3015, title: 'Ginem', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3016, title: 'Idi i ne budi ljude', artist: 'Ceca (Pop Version)', type: 'Ženske Zabavne' },
  { id: 3017, title: 'Kolacici', artist: 'Marina Perazić', type: 'Ženske Zabavne' },
  { id: 3018, title: 'Majstor za poljupce', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3019, title: 'Cekala sam', artist: 'Jadranka Stojaković', type: 'Ženske Zabavne' },
  { id: 3020, title: 'Cuvam te', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3021, title: 'Sanjam te jos', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3022, title: 'Ljubav je samo rec', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3023, title: 'Ako odes ti', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3024, title: 'Vejte snegovi', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3025, title: 'Princeza', artist: 'Bebi Dol', type: 'Ženske Zabavne' },
  { id: 3026, title: 'I will always love you', artist: 'Whitney Houston', type: 'Ženske Zabavne' },
  { id: 3027, title: 'Eternal', artist: 'Bangles', type: 'Ženske Zabavne' },
  { id: 3028, title: 'Without', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3029, title: 'Woman in love', artist: 'Barbra Streisand', type: 'Ženske Zabavne' },
  { id: 3030, title: 'Smooth operator', artist: 'Sade', type: 'Ženske Zabavne' },
  { id: 3031, title: 'Sweet dreams', artist: 'Eurythmics', type: 'Ženske Zabavne' },
  { id: 3032, title: 'My heart will', artist: 'Celine Dion', type: 'Ženske Zabavne' },
  { id: 3033, title: 'Pomozi mi', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3034, title: 'Ja cinim sve', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3035, title: 'It must have been love', artist: 'Roxette', type: 'Ženske Zabavne' },
  { id: 3036, title: 'Da je sladje zaspati', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3037, title: 'Gutljaj vina', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3038, title: 'Crni ples', artist: 'Oktobar 1864', type: 'Ženske Zabavne' },
  { id: 3039, title: 'Magla', artist: 'Josipa Lisac', type: 'Ženske Zabavne' },
  { id: 3040, title: 'Ozenises se ti', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3041, title: 'Kralj', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3042, title: 'Baklje ivanjske', artist: 'Doris Dragović', type: 'Ženske Zabavne' },
  { id: 3043, title: 'Rukuju se', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3044, title: 'Ni zadnji ni prvi', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3045, title: 'Kad volis', artist: 'Karamela', type: 'Ženske Zabavne' },
  { id: 3046, title: 'Spremna sam', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3047, title: 'Ti si mene Nina', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3048, title: 'Sam', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3049, title: 'Uzalud se budim', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3050, title: 'Da li znas da te ne volim', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3051, title: 'Takvi kao ti', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3052, title: 'Da te volim', artist: 'Aleksandra Kovac', type: 'Ženske Zabavne' },
  { id: 3053, title: 'Kuca za spas', artist: 'Goca Tržan', type: 'Ženske Zabavne' },
  { id: 3054, title: 'Tajna veza', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3055, title: 'Mace moje', artist: 'Lepa Brena (Pop)', type: 'Ženske Zabavne' },
  { id: 3056, title: 'Lozinka za kraj', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3057, title: 'Danas sam luda', artist: 'Josipa Lisac', type: 'Ženske Zabavne' },
  { id: 3058, title: 'To Doris', artist: 'Doris D.', type: 'Ženske Zabavne' },
  { id: 3059, title: 'Kao ti', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3060, title: 'Pisi mi', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3061, title: 'Sudnji dan', artist: 'Doris i Magazin', type: 'Ženske Zabavne' },
  { id: 3062, title: 'Predaleko', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3063, title: 'Opijum', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3064, title: 'Jabuke i vino', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3065, title: 'Nadji me', artist: 'Oktobar 1864', type: 'Ženske Zabavne' },
  { id: 3066, title: 'Okreni se', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3067, title: 'Black Velvet', artist: 'Alannah Myles', type: 'Ženske Zabavne' },
  { id: 3068, title: 'Ne umem da nevolim', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3069, title: 'Plakaces ko zena', artist: 'Goca Tržan', type: 'Ženske Zabavne' },
  { id: 3070, title: 'Vino i gitare', artist: 'Gabi Novak', type: 'Ženske Zabavne' },
  { id: 3071, title: 'Ono sve sto znas o meni', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3072, title: 'Nemam snage da se pomirim', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3073, title: 'Stoperka', artist: 'Goca Tržan', type: 'Ženske Zabavne' },
  { id: 3074, title: 'Sakom od sto', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3075, title: 'Zeljo moja', artist: 'Doris Dragović', type: 'Ženske Zabavne' },
  { id: 3076, title: 'Tri sam ti zime', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3077, title: 'Ti zelja mog zivota', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3078, title: 'Grad', artist: 'Goca Tržan', type: 'Ženske Zabavne' },
  { id: 3079, title: 'Milo moje', artist: 'Bisera V.', type: 'Ženske Zabavne' },
  { id: 3080, title: 'Put putujem', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3081, title: 'Carobno Jutro', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3084, title: 'Dat ce nam bog', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3085, title: 'Moram', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3086, title: 'My all', artist: 'Mariah Carey', type: 'Ženske Zabavne' },
  { id: 3087, title: 'Money', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3088, title: 'The winners takes it all', artist: 'ABBA', type: 'Ženske Zabavne' },
  { id: 3089, title: 'Jos te volim', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3090, title: 'Za dobra stara vremena', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3091, title: 'Denis', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3092, title: 'Unbreak my hearth', artist: 'Toni Braxton', type: 'Ženske Zabavne' },
  { id: 3093, title: 'Sreco necija', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3094, title: 'Suze biserne', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3095, title: 'Killing me softly', artist: 'Fugees', type: 'Ženske Zabavne' },
  { id: 3096, title: 'Dont cry for Louie', artist: 'Vaya Con Dios', type: 'Ženske Zabavne' },
  { id: 3097, title: 'Aria', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3098, title: 'Tek je 12', artist: 'ET', type: 'Ženske Zabavne' },
  { id: 3099, title: 'Da ti nisam bila dovoljna', artist: 'ET', type: 'Ženske Zabavne' },
  { id: 3100, title: 'Evo zima ce', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3101, title: 'Nazovi me', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3102, title: 'Ja samo pjevam', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3103, title: 'Zora je svanula', artist: 'Neda Ukraden', type: 'Ženske Zabavne' },
  { id: 3104, title: 'Ima nesto u tom sto me neces', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3105, title: 'No ordinary love', artist: 'Sade', type: 'Ženske Zabavne' },
  { id: 3106, title: 'Jorgovani', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3107, title: 'Kao so u moru', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3108, title: 'Ni da mora nestane', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3109, title: 'Nikad ne reci uskoro', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3110, title: 'Zagrli me', artist: 'Viktorija', type: 'Ženske Zabavne' },
  { id: 3111, title: 'Slatko ljuto kiselo', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3112, title: 'Jutro', artist: 'Jelena Tomašević', type: 'Ženske Zabavne' },
  { id: 3113, title: 'Haljina', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3114, title: 'Da se opet tebi vratim', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3115, title: 'Ne tice me se', artist: 'Magazin', type: 'Ženske Zabavne' },
  { id: 3116, title: 'Just the friend of mine', artist: 'Vaya Con Dios', type: 'Ženske Zabavne' },
  { id: 3117, title: 'Its in his kiss', artist: 'Cher', type: 'Ženske Zabavne' },
  { id: 3118, title: 'Za dobre i lose dane', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3119, title: 'Fins', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3120, title: 'Jedina', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3121, title: 'Budi dobar kao sto', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3122, title: 'Zemlja mojih snova', artist: 'Tijana Dapčević', type: 'Ženske Zabavne' },
  { id: 3124, title: 'Hajde da ludujemo ove noci', artist: 'Tajči', type: 'Ženske Zabavne' },
  { id: 3131, title: 'Mladicu moj', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3132, title: 'Daj ne pitaj', artist: 'Viktorija', type: 'Ženske Zabavne' },
  { id: 3133, title: 'Recka je na zidu', artist: 'Lidija', type: 'Ženske Zabavne' },
  { id: 3134, title: 'bjezi kiso sa prozora', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3135, title: 'Dvoje', artist: 'Neverne Bebe (Zenski vokal)', type: 'Ženske Zabavne' },
  { id: 3136, title: 'Muzika noci', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3137, title: 'Kofer ljubavi', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3141, title: 'Srce nije kamen', artist: 'Toše Proeski (Cover)', type: 'Ženske Zabavne' },
  { id: 3142, title: 'Dodirni mi kolena', artist: 'Zana', type: 'Ženske Zabavne' },
  { id: 3143, title: 'Potrazi me u pregradnu', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3144, title: 'Moje je ime sreca', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3146, title: 'Prastam', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3148, title: 'Cuvaj moje srce', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3155, title: 'Nisam', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3159, title: 'Zivim za to', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3160, title: 'Rekao si', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3161, title: 'Molitva', artist: 'Marija Šerifović', type: 'Ženske Zabavne' },
  { id: 3162, title: 'Hello', artist: 'Adele', type: 'Ženske Zabavne' },
  { id: 3163, title: 'Oprosti mala', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3164, title: 'a TI ME iznevjeri', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3166, title: 'Tako je to', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3175, title: 'Karta za jug', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3176, title: 'Udji Slobodno', artist: 'Lepa Brena (Pop)', type: 'Ženske Zabavne' },
  { id: 3177, title: 'Pazi kome zavidis', artist: 'Lepa Brena (Pop)', type: 'Ženske Zabavne' },
  { id: 3178, title: 'Tempera', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3179, title: 'Jos i danas zamirise tresnja', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3180, title: 'Daiew', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3181, title: 'Ne verujem da me ne volis', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3182, title: 'Sta to bese ljubav', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3183, title: 'Rodjeni', artist: 'Kaliopi', type: 'Ženske Zabavne' },
  { id: 3184, title: 'Jesam te pustila', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3185, title: 'Barakuda', artist: 'Viktorija', type: 'Ženske Zabavne' },
  { id: 3186, title: 'Uzmi boje', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3187, title: 'Da ima nas', artist: 'Neverne Bebe', type: 'Ženske Zabavne' },
  { id: 3188, title: 'Negativ', artist: 'Tijana Dapčević', type: 'Ženske Zabavne' },
  { id: 3189, title: 'Jos ti se nadam', artist: 'Emina J.', type: 'Ženske Zabavne' },
  { id: 3190, title: 'PRatim te', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3191, title: 'Tuzna pesma', artist: 'Neverne Bebe', type: 'Ženske Zabavne' },
  { id: 3192, title: 'Ako nikada', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3193, title: 'Tridesete', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3196, title: 'Oro', artist: 'Jelena Tomašević', type: 'Ženske Zabavne' },
  { id: 3199, title: 'Dobrodosao u klub', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3200, title: 'Pogled ispod obrva', artist: 'Severina', type: 'Ženske Zabavne' },
  { id: 3201, title: 'Gde dunav ljubi nebo', artist: 'Josipa Lisac', type: 'Ženske Zabavne' },
  { id: 3202, title: 'Stani duso', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3203, title: 'Strah me da te volim', artist: 'Hari Mata Hari (Cover)', type: 'Ženske Zabavne' },
  { id: 3204, title: 'Okeani', artist: 'Jelena Tomašević', type: 'Ženske Zabavne' },
  { id: 3205, title: 'Zazmuri', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3206, title: 'Stranac u noci', artist: 'Zenska Pop', type: 'Ženske Zabavne' },
  { id: 3207, title: 'Nisi moj', artist: 'Aleksandra Radović', type: 'Ženske Zabavne' },
  { id: 3208, title: 'Oktobar', artist: 'Oktobar 1864', type: 'Ženske Zabavne' },
  { id: 3209, title: 'Otpisi sve', artist: 'Pop', type: 'Ženske Zabavne' },
  { id: 3210, title: 'Dodirniod stakla', artist: 'Nina Badrić', type: 'Ženske Zabavne' },
  { id: 3211, title: 'Im so excited', artist: 'Pointer Sisters', type: 'Ženske Zabavne' },
  { id: 3212, title: 'Kosava', artist: 'Jelena Tomašević', type: 'Ženske Zabavne' },
  { id: 3213, title: 'Ti mozes sve', artist: 'Marija Šerifović', type: 'Ženske Zabavne' },
  { id: 3213, title: 'Ti mozes sve', artist: 'Marija Šerifović', type: 'Ženske Zabavne' },

  // -------------------------------------------------------------
  // 2. MUSKE NARODNE (217 PESAMA)
  // -------------------------------------------------------------
  { id: 1001, title: 'Kafanski sviracu', artist: 'S. Bajramovich', type: 'Muške Narodne' },
  { id: 1002, title: 'Jednu cašu drzim u ruci', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1003, title: 'Mene je ucilo vreme', artist: 'Halid M.', type: 'Muške Narodne' },
  { id: 1004, title: 'Cerge', artist: 'Zlatko P.', type: 'Muške Narodne' },
  { id: 1005, title: 'Adio', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1006, title: 'Pijem', artist: 'Miki Jevremović', type: 'Muške Narodne' },
  { id: 1007, title: 'Djelem djelem', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1008, title: 'Secas li se one noci', artist: 'Haris Dž.', type: 'Muške Narodne' },
  { id: 1009, title: 'Pije mi se', artist: 'Mile K.', type: 'Muške Narodne' },
  { id: 1010, title: 'Sacuvaj tajnu', artist: 'Duško K.', type: 'Muške Narodne' },
  { id: 1011, title: 'Kako mi nedostajes', artist: 'Haris Dž.', type: 'Muške Narodne' },
  { id: 1012, title: 'Bez tebe je gorko vino', artist: 'Duško K.', type: 'Muške Narodne' },
  { id: 1013, title: 'Prvi poljubac', artist: 'Halid B.', type: 'Muške Narodne' },
  { id: 1014, title: 'U godini jedan dan', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1015, title: 'Miljacka', artist: 'Halid B.', type: 'Muške Narodne' },
  { id: 1016, title: 'Ova noc ima cudnu moc', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1017, title: 'Bilo cija', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1018, title: 'Dijana ljubavi', artist: 'Ferid A.', type: 'Muške Narodne' },
  { id: 1019, title: 'Snezana', artist: 'Šaban Š.', type: 'Muške Narodne' },
  { id: 1020, title: 'Nisam te se nagledao', artist: 'Zoran G.', type: 'Muške Narodne' },
  { id: 1021, title: 'Kisa je padala', artist: 'Ljubomir Đ.', type: 'Muške Narodne' },
  { id: 1022, title: 'Uspeo sam u zivotu', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1023, title: 'Gde cu sad moja ruzo', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1024, title: 'Rastajemo se mi', artist: 'Miroslav I.', type: 'Muške Narodne' },
  { id: 1025, title: 'Dva galeba bela', artist: 'Šaban Š.', type: 'Muške Narodne' },
  { id: 1026, title: 'Sve sam ti dao', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1027, title: 'Lako ti je mene varati', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1028, title: 'Zar ja da ti brisem suze', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1029, title: 'Crna zemlja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1030, title: 'Seti me se jednog dana', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1031, title: 'I pod sjajem ruz zvezda', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1032, title: 'Nocas mi srce pati', artist: 'Toma Z.', type: 'Muške Narodne' },
  { id: 1033, title: 'Grlica', artist: 'Željko S. (Folk version)', type: 'Muške Narodne' },
  { id: 1034, title: 'Narcis', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1035, title: 'Nesanica', artist: 'Ivkova slava', type: 'Muške Narodne' },
  { id: 1036, title: 'Janicar', artist: 'Cune Gojković', type: 'Muške Narodne' },
  { id: 1037, title: 'Dajte vina', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1038, title: 'Ja ne pijem', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1039, title: 'Okreni moj broj', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1040, title: 'I kad me svi zaborave', artist: 'Marinko R.', type: 'Muške Narodne' },
  { id: 1041, title: 'Odjila', artist: 'Romsko-Folk', type: 'Muške Narodne' },
  { id: 1042, title: 'Laze mjesec', artist: 'Haris Dž.', type: 'Muške Narodne' },
  { id: 1043, title: 'Zadnja casa', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1044, title: 'Grle me', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1045, title: 'Jesul dunje procvale', artist: 'Haris Dž.', type: 'Muške Narodne' },
  { id: 1046, title: 'A u medjuvremenu', artist: 'OK Band (Folk)', type: 'Muške Narodne' },
  { id: 1047, title: 'Sto cu casa polomiti', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1048, title: 'Ja stalno pijem', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1049, title: 'Sve je mojke tvoje', artist: 'Aca Lukas', type: 'Muške Narodne' },
  { id: 1050, title: 'Neznanka', artist: 'Predrag Gojković Cune', type: 'Muške Narodne' },
  { id: 1051, title: 'Od boga si stvorena', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1052, title: 'Pesma od bola', artist: 'Aca Lukas', type: 'Muške Narodne' },
  { id: 1053, title: 'Ti meni lazes sve', artist: 'Duško K.', type: 'Muške Narodne' },
  { id: 1054, title: 'Lele lele', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1055, title: 'Dunjo moja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1056, title: 'Ciganin sam voljena', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1057, title: 'Maro Suzo', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1058, title: 'Emina', artist: 'Vajta/Narodna split', type: 'Muške Narodne' },
  { id: 1059, title: 'Fato mori', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1060, title: 'Soko banja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1061, title: 'Case lomim', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1062, title: 'Od kad sam se rodio', artist: 'Sinan S.', type: 'Muške Narodne' },
  { id: 1063, title: 'Cajorije sukarije', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1064, title: 'Kafanska pevacica', artist: 'Željko Samardžić', type: 'Muške Narodne' },
  { id: 1065, title: 'Zoko moja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1066, title: 'Neznanka', artist: 'Cune', type: 'Muške Narodne' },
  { id: 1067, title: 'Dudo', artist: 'Luis', type: 'Muške Narodne' },
  { id: 1068, title: 'Crni gavrane', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1069, title: 'Jedna zena a dva druga', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1070, title: 'Crna zeno sa ocima plavim', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1071, title: 'Ostale su suze', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1072, title: 'Ivana', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1073, title: 'Ona je prica', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1074, title: 'Oprosti izvini', artist: 'Željko Samardžić', type: 'Muške Narodne' },
  { id: 1075, title: 'I zanesen tom lepotom', artist: 'Halid B.', type: 'Muške Narodne' },
  { id: 1076, title: 'Idi moram da ti kazem', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1077, title: 'Sve cu tuge', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1078, title: 'Gordana', artist: 'Šaban Š.', type: 'Muške Narodne' },
  { id: 1079, title: 'Radjaj sinove', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1080, title: 'Marija', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1081, title: 'Sto se mala uobrazi', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1082, title: 'ko se s nama druzi', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1083, title: 'Nocni zivot', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1084, title: 'koje si vere nevero moja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1085, title: 'Djavolica', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1086, title: 'Giljam dade', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1087, title: 'Magda', artist: 'Luis', type: 'Muške Narodne' },
  { id: 1088, title: 'A tebe nema', artist: 'Zorica B. (Cover)', type: 'Muške Narodne' },
  { id: 1089, title: 'Ramo Ramo', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1090, title: 'Casa po casa', artist: 'Šaban Š.', type: 'Muške Narodne' },
  { id: 1091, title: 'Sit kafano', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1092, title: 'zajedno do kraja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1093, title: 'posao sam majko u tudju zemlju', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1094, title: 'Ispod palme', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1095, title: 'Hej evo me', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1096, title: 'Makedonsko devojce', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1097, title: 'Nazdravite drugovi', artist: 'Hašim K.', type: 'Muške Narodne' },
  { id: 1098, title: 'Sar planina', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1099, title: 'ja ti dodjoh kao gost', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1100, title: 'Jos me peku suze tvoje', artist: 'Ljubomir Đ.', type: 'Muške Narodne' },
  { id: 1101, title: 'Bitola', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1102, title: 'Milke duso', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1103, title: 'Slutim', artist: 'Željko Samardžić (Folk)', type: 'Muške Narodne' },
  { id: 1104, title: 'Jesul dunje procvale', artist: 'Haris Dž.', type: 'Muške Narodne' },
  { id: 1105, title: 'Taja casa', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1106, title: 'Ajde Jano', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1107, title: 'Izdaje me snaga', artist: 'Šaban Š.', type: 'Muške Narodne' },
  { id: 1108, title: 'Eleno kerko', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1109, title: 'Topla zima', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1110, title: 'Niska banja', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1111, title: 'Necu necu dijamante', artist: 'Halid B.', type: 'Muške Narodne' },
  { id: 1112, title: 'Sviraj Feate', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1113, title: 'Opa opa', artist: 'Luis', type: 'Muške Narodne' },
  { id: 1114, title: 'Ugasila si me', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1115, title: 'Uz Moravu', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1116, title: 'Mostovi na Moraci', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1117, title: 'Pljevaljski tamburasi', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1118, title: 'Jedna reka', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1119, title: 'Ti si zena mog zivota', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1120, title: 'Spomenar', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1121, title: 'Sanja', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1122, title: 'Danijela', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1123, title: 'Moj golube', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1124, title: 'Ja hocu sad', artist: 'Džej R.', type: 'Muške Narodne' },
  { id: 1125, title: 'Crna kosa oko plavo', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1126, title: 'Aman aman', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1127, title: 'Cudna zena', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1128, title: 'Koliba il dvor', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1129, title: 'Neno', artist: 'Luis', type: 'Muške Narodne' },
  { id: 1130, title: 'Sota', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1131, title: 'Jarane jarane', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1132, title: 'Voli me danas', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1133, title: 'Ceri moja aliji', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1134, title: 'Mazo', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1135, title: 'Bele ruze', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1136, title: 'Otisao vratio se', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1137, title: 'Nije ljubav fotografija', artist: 'Saša Matić', type: 'Muške Narodne' },
  { id: 1138, title: 'Plava ciganko', artist: 'Mile K.', type: 'Muške Narodne' },
  { id: 1139, title: 'Prava ljubav', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1140, title: 'Bezobrazno zelene', artist: 'Željko Samardžić', type: 'Muške Narodne' },
  { id: 1141, title: 'Dajte jednu losu', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1142, title: 'Vreteno', artist: 'Željko Joksimović (Folk)', type: 'Muške Narodne' },
  { id: 1143, title: 'Ruznarin', artist: 'Saša Matić', type: 'Muške Narodne' },
  { id: 1144, title: 'Ko te ljubi ovih dana', artist: 'Saša Matić', type: 'Muške Narodne' },
  { id: 1145, title: 'Sampanjac', artist: 'Mile K.', type: 'Muške Narodne' },
  { id: 1146, title: 'Jelena', artist: 'Aca Lukas', type: 'Muške Narodne' },
  { id: 1147, title: 'Usne boje vina', artist: 'Boban Rajović', type: 'Muške Narodne' },
  { id: 1148, title: 'Dance svileno maramce', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1149, title: 'Luckasta si ti', artist: 'Miroslav Ilić', type: 'Muške Narodne' },
  { id: 1150, title: 'Govori se da me varas', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1151, title: 'Kad te vidim na sokaku', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1152, title: 'Daj mi casu rakije', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1153, title: 'Kraj jezera', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1154, title: 'Marina', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1155, title: 'Dunave', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1156, title: 'Kad ja podjoh na Bembasu', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1157, title: 'Osam tamburasa', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1159, title: 'Ti bi htela pesmom', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1160, title: 'Imam jednu zelju', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1161, title: 'Ima dana', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1162, title: 'Milkina kuca', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1163, title: 'Fijaker stari', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1164, title: 'Tiho noci', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1165, title: 'U tem Somboru', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1166, title: 'U ranu zoru', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1167, title: 'Pred cenkinom kucom', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1168, title: 'Moja mala', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1169, title: 'Ne vredi plakati', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1170, title: 'Stano mori', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1171, title: 'Zvezda tjera', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1172, title: 'Mali pijac', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1173, title: 'Moj konjicu', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1174, title: 'Negde u daljini', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1175, title: 'Emina', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1176, title: 'Rujna zora', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1177, title: 'Cujes seko', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1178, title: 'I dodji lolo', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1179, title: 'Rekla nana', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1180, title: 'Tri metera somota', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1181, title: 'Zajdi zajdi', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1182, title: 'Jesenje lisce', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1183, title: 'Gruzanke devojke', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1184, title: 'Stade se', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1185, title: 'Leno leno', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1186, title: 'Nije mene duso ubilo', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1187, title: 'Imao sam', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1188, title: 'Ti za ljubav nisi', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1189, title: 'Ko te ima taj te nema', artist: 'Zvonko Bogdan', type: 'Muške Narodne' },
  { id: 1190, title: 'Poslednji boem', artist: 'Toma Zdravković', type: 'Muške Narodne' },
  { id: 1191, title: 'Ti mene ne volis', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1192, title: 'Skitnica', artist: 'Marinko Rokvić', type: 'Muške Narodne' },
  { id: 1193, title: 'Polomicu case od kristala', artist: 'Miroslav Ilić', type: 'Muške Narodne' },
  { id: 1194, title: 'Iz krajine lepa vlajna', artist: 'Novica Negovanović', type: 'Muške Narodne' },
  { id: 1195, title: 'Dorulje', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1196, title: 'Lju Lju LJu', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1197, title: 'Tuata sara', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1198, title: 'Svadba svadba', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1199, title: 'Kume brate', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1200, title: 'Zlatna burma', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1201, title: 'Danas majko', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1202, title: 'Izvor voda', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1203, title: 'Obrase se vinogradi', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1204, title: 'Pastirica', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1205, title: 'Pevaj ujko', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1206, title: 'Pod Javorom', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1207, title: 'Trepetljika', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1208, title: 'Rujna zora', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1209, title: 'Bolovala mlada Vinka', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1210, title: 'Mostovi na Moraci', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1211, title: 'Pljevaljski tamburasi', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1212, title: 'Leti leti bijeli golube', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1213, title: 'Poljece soko', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1214, title: 'Ruzo rumena', artist: 'Dragan Jovanović', type: 'Muške Narodne' },
  { id: 1215, title: 'Prodjoh skoro C gorom', artist: 'Popularna', type: 'Muške Narodne' },
  { id: 1216, title: 'Kralj Nikola', artist: 'Narodna', type: 'Muške Narodne' },
  { id: 1217, title: 'Gledala sam s koma plava', artist: 'Tradicionalna', type: 'Muške Narodne' },
  { id: 1217, title: 'Gledala sam s koma plava', artist: 'Tradicionalna', type: 'Muške Narodne' },

  // -------------------------------------------------------------
  // 4. STARIJE ZABAVNE / EVERGREEN (245+ PESAMA)
  // -------------------------------------------------------------
  { id: 4001, title: 'Jedina moja', artist: 'YU grupa', type: 'Starije Zabavne' },
  { id: 4002, title: 'Vasa Ladacki', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4003, title: 'Crni leptir', artist: 'YU grupa', type: 'Starije Zabavne' },
  { id: 4004, title: 'Podlugovi', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4005, title: 'Dao sam ti dusu', artist: 'Alen Slavica', type: 'Starije Zabavne' },
  { id: 4006, title: 'Ne zelis kraj', artist: 'Divlje Jagode', type: 'Starije Zabavne' },
  { id: 4007, title: 'Magdalena', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4008, title: 'Strah me da te volim', artist: 'Hari Mata Hari', type: 'Starije Zabavne' },
  { id: 4009, title: 'Ti si mi u krvi', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4010, title: 'Nekako s proljeca', artist: 'Crvena Jabuka & Balašević', type: 'Starije Zabavne' },
  { id: 4011, title: 'Na tvojim usnama', artist: 'Galija', type: 'Starije Zabavne' },
  { id: 4013, title: 'Ti samo budi', artist: 'Generacija 5', type: 'Starije Zabavne' },
  { id: 4014, title: 'Kao ptica na mom dlanu', artist: 'Piloti', type: 'Starije Zabavne' },
  { id: 4015, title: 'Obrisi suze draga', artist: 'Boban Zdravković (Pop)', type: 'Starije Zabavne' },
  { id: 4016, title: 'Zazmuri', artist: 'Bajaga', type: 'Starije Zabavne' },
  { id: 4017, title: 'Dodjavola sve', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4018, title: 'Umiru jeleni', artist: 'Poslednja Igra Leptira', type: 'Starije Zabavne' },
  { id: 4019, title: 'Pitaju me pitaju', artist: 'Oliver Mandić', type: 'Starije Zabavne' },
  { id: 4020, title: 'Dzezery', artist: 'Zabavna', type: 'Starije Zabavne' },
  { id: 4021, title: 'Zaboravljeni', artist: 'Piloti', type: 'Starije Zabavne' },
  { id: 4022, title: 'Oprosti Bebek', artist: 'Željko Bebek', type: 'Starije Zabavne' },
  { id: 4024, title: 'Vino na usnama', artist: 'Vlado Kalember', type: 'Starije Zabavne' },
  { id: 4025, title: 'Godine prolaze', artist: 'Parni Valjak', type: 'Starije Zabavne' },
  { id: 4026, title: 'Sele moja', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4027, title: 'Moji su drugovi', artist: 'Bajaga', type: 'Starije Zabavne' },
  { id: 4029, title: 'Deny', artist: 'Cod', type: 'Starije Zabavne' },
  { id: 4031, title: 'Stare trube', artist: 'Galija', type: 'Starije Zabavne' },
  { id: 4033, title: 'Avionu slomicu ti', artist: 'Riblja Čorba', type: 'Starije Zabavne' },
  { id: 4035, title: 'Dunje zute', artist: 'Indexi', type: 'Starije Zabavne' },
  { id: 4036, title: 'Nije za nju', artist: 'Oliver Mandić', type: 'Starije Zabavne' },
  { id: 4037, title: 'Malinkonija', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4038, title: 'Naj NAj', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4041, title: 'Lose vino', artist: 'Bijelo Dugme', type: 'Starije Zabavne' },
  { id: 4043, title: 'Dzipsy magic', artist: 'Vlatko Stefanovski', type: 'Starije Zabavne' },
  { id: 4044, title: 'Daj mi samo ovu noc', artist: 'Generacija 5', type: 'Starije Zabavne' },
  { id: 4045, title: 'Cesarica', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4046, title: 'Jedne noci u decembru', artist: 'Kemal Monteno', type: 'Starije Zabavne' },
  { id: 4047, title: 'Ti mozes sve', artist: 'Marija Šerifović (Rock version)', type: 'Starije Zabavne' },
  { id: 4049, title: 'Nasoj ljubavi je kraj', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4050, title: 'Iznad planeta', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4051, title: 'Sve ove godine', artist: 'Indexi', type: 'Starije Zabavne' },
  { id: 4052, title: 'krivo je more', artist: 'Divlje Jagode', type: 'Starije Zabavne' },
  { id: 4053, title: 'Poeta', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4054, title: 'Moj galebe', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4057, title: 'Mornar', artist: 'YU grupa', type: 'Starije Zabavne' },
  { id: 4060, title: 'Kristina', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4061, title: 'Kotor', artist: 'Galija', type: 'Starije Zabavne' },
  { id: 4064, title: 'Bambina', artist: 'Neki To Vole Vruće', type: 'Starije Zabavne' },
  { id: 4065, title: 'Brzi voz', artist: 'Galija', type: 'Starije Zabavne' },
  { id: 4066, title: 'Kokain', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4068, title: 'Zar nije te stid', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4069, title: 'Nebo zna', artist: 'Neverne Bebe', type: 'Starije Zabavne' },
  { id: 4070, title: 'Neko te ima nocas', artist: 'Van Gogh', type: 'Starije Zabavne' },
  { id: 4072, title: 'Jasmina', artist: 'Džej (Pop-Rock version)', type: 'Starije Zabavne' },
  { id: 4074, title: 'Za ljubav treba imat dusu', artist: 'Atomsko Sklonište', type: 'Starije Zabavne' },
  { id: 4075, title: '442 do Beograda', artist: 'Bajaga', type: 'Starije Zabavne' },
  { id: 4076, title: 'Starim ja', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4079, title: 'Bobane', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4080, title: 'Lazu lazu me', artist: 'Bijelo Dugme', type: 'Starije Zabavne' },
  { id: 4081, title: 'Buba Maro moja', artist: 'YU grupa', type: 'Starije Zabavne' },
  { id: 4082, title: 'Hrizantema', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4083, title: 'Sanjam', artist: 'Indexi', type: 'Starije Zabavne' },
  { id: 4084, title: 'Bacila je sve niz reku', artist: 'Indexi', type: 'Starije Zabavne' },
  { id: 4085, title: 'Devojko mala', artist: 'Đuza Stojiljković', type: 'Starije Zabavne' },
  { id: 4086, title: 'Petao', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4087, title: 'Kako si topla i mila', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4088, title: 'Laku noc sviraci', artist: 'Željko Bebek', type: 'Starije Zabavne' },
  { id: 4089, title: 'Smejem se a plakao bi', artist: 'Oliver Mandić', type: 'Starije Zabavne' },
  { id: 4090, title: 'Zaboravi', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4094, title: 'Katarina', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4095, title: 'Sinoc sam', artist: 'Zenska Pop', type: 'Starije Zabavne' },
  { id: 4096, title: 'Brod u boci', artist: 'Petar Grašo', type: 'Starije Zabavne' },
  { id: 4097, title: 'Dolazim za 5 min', artist: 'Generacija 5', type: 'Starije Zabavne' },
  { id: 4098, title: 'green grass', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4099, title: 'Zbog jedne divne crne zene', artist: 'Kićo Slabinac', type: 'Starije Zabavne' },
  { id: 4100, title: 'Litar vina', artist: 'Galija', type: 'Starije Zabavne' },
  { id: 4101, title: 'Pjesma lagana', artist: 'Parni Valjak', type: 'Starije Zabavne' },
  { id: 4102, title: 'Vece ne mirise na rakove', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4103, title: 'Samo jedan dan zivota', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4104, title: 'Ruzica si bila', artist: 'Bijelo Dugme', type: 'Starije Zabavne' },
  { id: 4105, title: 'Tamara', artist: 'Bajaga', type: 'Starije Zabavne' },
  { id: 4106, title: 'To mi radi', artist: 'Crvena Jabuka', type: 'Starije Zabavne' },
  { id: 4108, title: 'Jesen u meni', artist: 'Parni Valjak', type: 'Starije Zabavne' },
  { id: 4109, title: 'Nema nama sna', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4110, title: 'S kim cekas dan', artist: 'Cukić', type: 'Starije Zabavne' },
  { id: 4111, title: 'Ne lomi me', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4113, title: 'Stvari lagane', artist: 'Boris Novković', type: 'Starije Zabavne' },
  { id: 4114, title: 'Badnje vece', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4131, title: 'Od tuge cu za tobom', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4139, title: 'Metak', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4193, title: 'Ostala si uvek ista', artist: 'Mišo Kovač', type: 'Starije Zabavne' },
  { id: 4194, title: 'Neki novi klinci', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4196, title: 'Poludecu', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4199, title: 'Stvari lagane', artist: 'Boris Novković', type: 'Starije Zabavne' },
  { id: 4200, title: 'Sve moje jeseni', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4202, title: 'Dunavom jos', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4203, title: 'Moj beli labude', artist: 'Prljavo Kazalište', type: 'Starije Zabavne' },
  { id: 4204, title: 'S kim cekas dan', artist: 'Cukić', type: 'Starije Zabavne' },
  { id: 4205, title: 'Kako si topla i mila', artist: 'Čolić', type: 'Starije Zabavne' },
  { id: 4206, title: 'Badnje vece', artist: 'Balašević', type: 'Starije Zabavne' },
  { id: 4207, title: 'Da li znas da te volim', artist: 'Dado Topić', type: 'Starije Zabavne' },
  { id: 4208, title: 'Zivot je more', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4217, title: 'Kada padne noc', artist: 'Riblja Čorba', type: 'Starije Zabavne' },
  { id: 4234, title: 'Umoran', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4241, title: 'Oktobar', artist: 'Oktobar 1864', type: 'Starije Zabavne' },
  { id: 4245, title: 'Smjehom strah', artist: 'Merlin', type: 'Starije Zabavne' },
  { id: 4246, title: 'A kad postanem pepeo', artist: 'Neverne Bebe', type: 'Starije Zabavne' },
  { id: 4247, title: 'Amajlija', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4248, title: 'Andjele Vlado', artist: 'Vlado Georgiev', type: 'Starije Zabavne' },
  { id: 4249, title: 'April u BGD', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4250, title: 'Bajka o ljubavi Dado', artist: 'Dado Topić', type: 'Starije Zabavne' },
  { id: 4251, title: 'Balada Zeljko', artist: 'Željko Samardžić', type: 'Starije Zabavne' },
  { id: 4252, title: 'Bas ti lepo stoje suze', artist: 'Hari Mata Hari', type: 'Starije Zabavne' },
  { id: 4253, title: 'Besame mucho', artist: 'Classic', type: 'Starije Zabavne' },
  { id: 4254, title: 'Cija si Tose', artist: 'Toše Proeski', type: 'Starije Zabavne' },
  { id: 4255, title: 'Cuskije', artist: 'Dino Merlin', type: 'Starije Zabavne' },
  { id: 4256, title: 'Daj mi vina da se napijem', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4257, title: 'Deset godina', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4258, title: 'Evo ima godina', artist: 'Regata', type: 'Starije Zabavne' },
  { id: 4259, title: 'Habanera', artist: 'Classic', type: 'Starije Zabavne' },
  { id: 4260, title: 'Hitna', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4261, title: 'Hotel Balkan', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4262, title: 'Igra bez granica', artist: 'Toše Proeski', type: 'Starije Zabavne' },
  { id: 4263, title: 'Ima nesto u tom sto me neces', artist: 'Nina Badrić', type: 'Starije Zabavne' },
  { id: 4264, title: 'jedina moja', artist: 'YU grupa', type: 'Starije Zabavne' },
  { id: 4265, title: 'Kad mi dodjes ti...Oliver', artist: 'Oliver Dragojević', type: 'Starije Zabavne' },
  { id: 4266, title: 'Kako je dobro videti te', artist: 'Novi Fosili', type: 'Starije Zabavne' },
  { id: 4267, title: 'Kao domine', artist: 'Neverne Bebe', type: 'Starije Zabavne' },
  { id: 4268, title: 'Kao letnje kise', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4269, title: 'Korak do dna', artist: 'Saša Kovačević', type: 'Starije Zabavne' },
  { id: 4270, title: 'Kremen', artist: 'Dino Merlin', type: 'Starije Zabavne' },
  { id: 4271, title: 'Krila leptira', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4272, title: 'Kupi me sa dve tri', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4273, title: 'Lampioni Knez', artist: 'Knez', type: 'Starije Zabavne' },
  { id: 4274, title: 'Lazu te', artist: 'Amadeus Band', type: 'Starije Zabavne' },
  { id: 4275, title: 'Ledja o ledja', artist: 'Željko Joksimović', type: 'Starije Zabavne' },
  { id: 4276, title: 'Lejla hari', artist: 'Hari Mata Hari', type: 'Starije Zabavne' },
  { id: 4277, title: 'Letnje kise', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4278, title: 'Linija zivota', artist: 'Željko Joksimović', type: 'Starije Zabavne' },
  { id: 4279, title: 'Ljubi ljubi Ljubice', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4280, title: 'Malena', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4281, title: 'Marija', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4282, title: 'Mesec u vodi', artist: 'Željko Samardžić', type: 'Starije Zabavne' },
  { id: 4283, title: 'Mi nismo mi', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4284, title: 'Michelle', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4285, title: 'Milo za drago', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4286, title: 'Mi nismo sami', artist: 'Film', type: 'Starije Zabavne' },
  { id: 4287, title: 'Moj je zivot Svicarska', artist: 'Dino Merlin', type: 'Starije Zabavne' },
  { id: 4288, title: 'mokre ulice', artist: 'Dejan Cukić', type: 'Starije Zabavne' },
  { id: 4289, title: 'Nije do mene', artist: 'Željko Joksimović', type: 'Starije Zabavne' },
  { id: 4290, title: 'Odlazi', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4291, title: 'Okano', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4292, title: 'Ostavi suze za kraj', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4293, title: 'Petak na subotu', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4294, title: 'Pevaj', artist: 'Ogi Radivojević', type: 'Starije Zabavne' },
  { id: 4295, title: 'Pogledi u tani', artist: 'Toše Proeski', type: 'Starije Zabavne' },
  { id: 4296, title: 'Protina kci', artist: 'Đorđe Balašević', type: 'Starije Zabavne' },
  { id: 4297, title: 'Ruka za spas', artist: 'Saša Kovačević', type: 'Starije Zabavne' },
  { id: 4298, title: 'Ruzice ruska', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4299, title: 'S tobom je prava stvar', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4300, title: 'Sta bi prijatelji moji', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4301, title: 'Sta ce meni vise od toga', artist: 'Željko Samardžić', type: 'Starije Zabavne' },
  { id: 4302, title: 'Sto ja volim taj sex', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4303, title: 'Sve je laz', artist: 'Dino Merlin', type: 'Starije Zabavne' },
  { id: 4304, title: 'Tamburasi s Dunava', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4305, title: 'Tebi je lako', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4306, title: 'Tvoje oci', artist: 'Zdravko Čolić', type: 'Starije Zabavne' },
  { id: 4307, title: 'Utorak', artist: 'Petar Grašo', type: 'Starije Zabavne' },
  { id: 4308, title: 'Vagabundo', artist: 'Goran Karan', type: 'Starije Zabavne' },
  { id: 4309, title: 'Vera od suvog zlata', artist: 'Miladin Šobić', type: 'Starije Zabavne' },
  { id: 4310, title: 'Vise te nema', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4311, title: 'Vjeruj', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4312, title: 'Vo kosi da ti spijam', artist: 'Toše Proeski', type: 'Starije Zabavne' },
  { id: 4313, title: 'Vreteno', artist: 'Željko Joksimović', type: 'Starije Zabavne' },
  { id: 4314, title: 'Vukota', artist: 'Zabranjeno Pušenje', type: 'Starije Zabavne' },
  { id: 4315, title: 'Zaboravljas', artist: 'Željko Joksimović', type: 'Starije Zabavne' },
  { id: 4316, title: 'Zauvek tvoj', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4317, title: 'Zbogom ljubavi', artist: 'Pop', type: 'Starije Zabavne' },
  { id: 4318, title: 'Zenica bluz', artist: 'Zabranjeno Pušenje', type: 'Starije Zabavne' },
];
